### ISSUE TITLE
Problèmes vus avec les journalistes

### ISSUE THREAD

**Issue by yannbug** [Celyan-SAS/Elastic-Search-news-agents#3]
- Donner accès à leur niveau de rôle utilisateur (ils ont le rôle "Auteur")
- Autre problèmes d'affichage/saisie des nouvelles sources Twitter et Facebook que tu as vu avec eux
- Préparer le passage de la collecte des flux sur Twitter sur deux listes en alternance pour contourner la limite

**Comment by SilverCelyan** [comment]
C'est à jour. Le role est a jour, twitter a une boucle pour quand il y aura plus de 15 lists, et les id ont été ajoutés a l'affichage dans l'admin.
Et c'est sur la prod.

**Comment by yannbug** [comment]
Ok super, on attend que la rédaction ajoute des sources et on refera un point lundi.
